version: '3.9'
services:
  licensingservice:
    image: umerfaruq/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licensing-service"
networks:
  backend:
    driver: bridge
